(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(TeX-electric-math '("\\(" . "\\)"))
 '(ansi-color-names-vector
   ["#3F3F3F" "#CC9393" "#7F9F7F" "#F0DFAF" "#8CD0D3" "#DC8CC3" "#93E0E3" "#FDF6E3"])
 '(blink-cursor-mode nil)
 '(bookmark-save-flag 1)
 '(browse-url-browser-function 'browse-url-generic)
 '(browse-url-generic-program (executable-find "x-www-browser"))
 '(cal-tex-24 t)
 '(case-fold-search t)
 '(column-number-mode t)
 '(company-quickhelp-color-background "#4F4F4F")
 '(company-quickhelp-color-foreground "#DCDCCC")
 '(confirm-kill-emacs nil)
 '(cua-auto-tabify-rectangles nil)
 '(cua-selection-mode t)
 '(current-language-environment "UTF-8")
 '(cursor-type 'bar)
 '(custom-enabled-themes '(material))
 '(custom-safe-themes
   '("7922b14d8971cce37ddb5e487dbc18da5444c47f766178e5a4e72f90437c0711" "e6df46d5085fde0ad56a46ef69ebb388193080cc9819e2d6024c9c6e27388ba9" default))
 '(debug-on-error nil)
 '(default-major-mode 'org-mode t)
 '(dired-guess-shell-alist-user nil)
 '(dired-omit-extensions
   '("~" ".a" ".aux" ".bbl" ".bcf" ".blg" ".elc" ".idx" ".lof" ".lot" ".toc" ".snm" ".nav" ".out" ".run.xml"))
 '(dired-omit-files-p t t)
 '(dired-omit-mode t t)
 '(dired-recursive-copies t)
 '(dired-recursive-deletes t)
 '(display-battery-mode t)
 '(display-time-24hr-format t)
 '(display-time-day-and-date t)
 '(display-time-format nil)
 '(display-time-mode t nil (time))
 '(display-time-use-mail-icon t)
 '(doc-view-continuous nil)
 '(elfeed-feeds
   '("http://pragmaticemacs.com/feed/" "https://www.reddit.com/r/emacs.rss" "https://nullprogram.com/feed/"
	 ("https://news.ycombinator.com/rss" hacker)
	 ("https://www.heise.de/developer/rss/news-atom.xml" heise)
	 ("https://www.reddit.com/r/programming.rss" programming)
	 ("https://www.reddit.com/r/emacs.rss" emacs)
	 ("https://www.reddit.com/r/golang.rss" golang)
	 ("https://www.reddit.com/r/java.rss" java)
	 ("https://www.reddit.com/r/javascript.rss" javascript)
	 ("https://www.reddit.com/r/typescript.rss" typescript)
	 ("https://www.reddit.com/r/clojure.rss" clojure)
	 ("https://www.reddit.com/r/python.rss" python)
	 ("https://www.reddit.com/r/aws.rss" aws)
	 ("https://www.reddit.com/r/googlecloud.rss" googlecloud)
	 ("https://www.reddit.com/r/azure.rss" azure)
	 ("https://www.reddit.com/r/devops.rss" devops)
	 ("https://www.reddit.com/r/kubernetes.rss" kubernetes)))
 '(fci-rule-color "#383838")
 '(fill-column 90)
 '(fringe-mode '(1 . 1) nil (fringe))
 '(global-auto-revert-mode t)
 '(global-font-lock-mode t nil (font-lock))
 '(global-hl-line-mode t nil (hl-line))
 '(global-prettify-symbols-mode t)
 '(graphviz-dot-auto-indent-on-semi nil)
 '(helm-autoresize-mode t)
 '(helm-full-frame t)
 '(hi-lock-mode t t (hi-lock))
 '(inhibit-startup-screen t)
 '(ispell-extra-args '("--reverse"))
 '(linum-format "%d ")
 '(magit-auto-revert-mode nil)
 '(make-backup-files nil)
 '(mark-diary-entries-in-calendar t)
 '(menu-bar-mode nil)
 '(mode-line-in-non-selected-windows t)
 '(nrepl-message-colors
   '("#CC9393" "#DFAF8F" "#F0DFAF" "#7F9F7F" "#BFEBBF" "#93E0E3" "#94BFF3" "#DC8CC3"))
 '(org-agenda-files
   '("~/Documents/rsync/swfu/lab-backup/lab-notes.org" "~/Documents/rsync/ytxx14/accounting.org"))
 '(org-ditaa-jar-path "/usr/bin/ditaa")
 '(org-time-stamp-custom-formats '("<%m/%d/%y>" . "<%m/%d/%y>"))
 '(package-selected-packages
   '(helm-ag rg rust-mode eglot flycheck elisp-slime-nav helm-slime slime elfeed-org elfeed zenburn-theme semi w3m wgrep-helm gnuplot gnuplot-mode helm-unicode elpy markdown-mode outline-magic yasnippet-classic-snippets material-theme graphviz-dot-mode nov csv-nav wgrep-ag nasm-mode web-mode yasnippet-snippets async helm auctex diminish helm-config helm-command helm-files ascii-art-to-unicode pyim yatemplate sicp org-pdfview org-chinese-utils htmlize helm-gtags helm-c-yasnippet exec-path-from-shell csv-mode cider-eval-sexp-fu use-package anzu))
 '(pdf-view-midnight-colors '("#DCDCCC" . "#383838"))
 '(read-mail-command 'ignore)
 '(recentf-max-menu-items 25)
 '(recentf-max-saved-items 25)
 '(recentf-mode t)
 '(recentf-save-file "~/.recentf")
 '(safe-local-variable-values
   '((From . "ltpi, Listing 52-4")
	 (From . blp4e)
	 (From . "tlpi, Listing 44-2")
	 (Usage . "/tmp/a.out 'string'")
	 (ref . https://unix\.stackexchange\.com/questions/187666/why-do-we-have-to-pass-the-file-name-twice-in-exec-functions/187673)
	 (ref . "http://stackoverflow.com/questions/5255320/reason-for-segmentation-fault")
	 (ref . "https://en.wikibooks.org/wiki/LaTeX/Title_Creation")
	 (TeX─master . t)
	 (reftex-default-bibliography "./os.bib")
	 (Ref . https://www\.arp242\.net/tmux\.html)))
 '(scheme-program-name "guile")
 '(scroll-bar-mode nil)
 '(select-enable-clipboard t)
 '(shell-command-with-editor-mode t)
 '(tool-bar-button-margin 1 t)
 '(tool-bar-mode nil)
 '(track-eol t)
 '(unibyte-display-via-language-environment t)
 '(version-control 'never)
 '(view-diary-entries-initially t)
 '(view-read-only t)
 '(visible-bell t)
 '(warning-minimum-level :emergency)
 '(warning-minimum-log-level :emergency)
 '(warning-suppress-types '((\(undo\ discard-info\))))
 '(x-stretch-cursor t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:height 240 :family "DejaVuSansMono Nerd Font"))))
 '(mode-line ((t (:height 160 :family "DejaVuSansMono Nerd Font"))))
 '(org-table ((t (:background "gray25" :foreground "light gray" :family "Noto Sans Mono CJK SC")))))
