#!/bin/bash

[[ -n "$1" ]] || { cat <<EOF
a2pdf - Convert any image into a black/white PDF file optionally with text annotation.

Usage: `basename $0` <Image> [Filter] [Threshold] [text] [x,y] [font size]

    Image - the image you want to tweak
   Filter - man mkbitmap for details
Threshold - man mkbitmap for details
     text - text to be added into the image
      x,y - coordinate of text to be added, default to '+300+30'
font size - default to 22
EOF
				   exit 4;
}

[[ -f "$1" ]] || { echo $1: 'Image file not found!'; exit 1; }

IMG="$1"
F="4"; [[ -n "$2" ]] && F=$2
T=".45"; [[ -n "$3" ]] && T=$3
TXT="$4"
XY='+300+30'; [[ -n "$5" ]] && XY=$5
FS='22'; [[ -n "$6" ]] && FS=$6

# https://tecadmin.net/how-to-extract-filename-extension-in-shell-script/
BASE="${IMG%.*}"

PPM="$BASE.ppm"
PBM="$BASE.pbm"
TIF="$BASE.tif"
PDF="$BASE.pdf"

convert $IMG $PPM 
mkbitmap -f$F -t$T -o $PBM $PPM

# convert -list font | grep CJK
[[ -n "$TXT" ]] && mogrify -pointsize $FS -font 'Noto-Sans-CJK-SC-Regular' -annotate $XY "$TXT" $PBM

ppm2tiff -c lzw $PBM $TIF
tiff2pdf -o $PDF -F $TIF
