#!/bin/bash

[[ -n "$3" ]] || { 
	cat <<EOF
Split a page from a PDF file, and crop it.

Usage: $0 <InPDF> <Page number> <OutPDF> [L T R B]"

InPDF - The input PDF file name
Page number - The number of to-be-cropped page
OutPDF - The output PDF file name
[L T R B] - Margins (Optional)
EOF
	exit 1;
}

INPDF="$1"
PAGE="$2"
OUTPDF="$3"
if [[ -n "$7" ]]; then
	MARGINS="$4 $5 $6 $7"
	pdftk $INPDF cat $PAGE output - | pdfcrop --margins "$MARGINS" --clip - $OUTPDF && mupdf $OUTPDF
else
	pdftk $INPDF cat $PAGE output - | pdfcrop --clip - $OUTPDF && mupdf $OUTPDF
fi
