#!/bin/bash

function usage(){
	cat <<EOF
$(basename $0) - Split a page out of a PDF file, and crop it.

Usage: $(basename $0) [-p page number] [-m L T R B] [-o outPDF] <inPDF>"

      inPDF - The input PDF file name
page number - The number of to-be-cropped page
     outPDF - The output PDF file name
    L T R B - Margins
EOF
}

#######color code########
ERR="31m"     # red
SUCCESS="32m" # green
WARN="33m"    # yellow
INFO="36m"    # blue

colorEcho(){
    echo -e "\033[${1}${@:2}\033[0m" 1>& 2
}

PAGE=1
MARGIN=(0 0 0 0)

while getopts :hp:m:o: OPT
do
	case $OPT in
		h) usage; exit 1 ;; 
		p) PAGE=$OPTARG ;;
		m) MARGIN=($OPTARG) ;;
		o) OUTPDF=$OPTARG ;;
		?) usage; exit 1 ;;
	esac
done
shift $(( OPTIND - 1 ))
OPTIND=1

INPDF="$@"

[[ -f "$INPDF" ]] || { colorEcho $ERR 'Error: Missing input file!'; usage; exit 1; }

[[ -n "$OUTPDF" ]] || OUTPDF="${INPDF%.*}-$PAGE.pdf"

pdftk $INPDF cat $PAGE output - | pdfcrop --margins "${MARGIN[*]}" --clip - $OUTPDF && mupdf $OUTPDF
