#!/bin/bash

if [[ -z "$3" ]]; then
    echo "Usage: $0 <InPDF> <Page number> <OutPDF> [L T R B]"
else
	INPDF="$1"
	PAGE="$2"
	OUTPDF="$3"
	MARGINS="$4 $5 $6 $7"
	
    pdftk $INPDF cat $PAGE output - | pdfcrop --margins "$MARGINS" --clip - $OUTPDF && mupdf $OUTPDF
fi

