#!/bin/bash

do_usage(){
    cat <<EOF
Usage: `basename $0` '<background> <signature> [g|ng] [x,y] [scale] [year] [month] [date]'

background - paper to sign on
 signature - signature file or text
      g|ng - show grid or not
       x,y - coordinate, e.g. '.6,.2', '.07,y' for the last page
     scale - scale to your signature (.2 looks good; 1.3 for the last page)
EOF
    exit 4;
}

do_check(){
	[[ -f "$1" ]] || { echo 'Missing background PDF file!'; do_usage; }
}

do_init(){
	BG="$1"
	SIG="$2"
	GRID='ng';  [[ -n "$3" ]] && GRID="$3"
	XY='12,6';  [[ -n "$4" ]] && XY="$4"
	SCALE='.2'; [[ -n "$5" ]] && SCALE="$5"
	Y='';       [[ -n "$6" ]] && Y="$6"
	M='';       [[ -n "$7" ]] && M="$7"
	D='';       [[ -n "$8" ]] && D="$8"

	TEX="${BG%.pdf}-signed.tex"
	PDF="${TEX%.tex}.pdf"
	LOG="${TEX%.tex}.log"
	AUX="${TEX%.tex}.aux"

	rm -f $PDF $TEX
}

do_grid(){
	cat <<EOF >> $TEX
\documentclass[tikz]{standalone}
\usetikzlibrary{backgrounds}
\usepackage{wx672ctex}
\begin{document}
\begin{tikzpicture}[inner sep=0]
    \node (bg) at (0,0) [anchor=south west]
		 {\includegraphics[width=\paperwidth]{$BG}};

	\begin{scope}
	%%% grid
	\draw[help lines,red,step=1] (0,0) grid (21,31);%
	\foreach \x in {0,1,...,20} { \node [anchor=south] at (\x,0) {\x}; }%
	\foreach \y in {0,1,...,30} { \node [anchor=west] at (0,\y) {\y}; }%
EOF
	if [[ -f "$SIG" ]]
	then
		# for first pages
		echo "\node at ($XY) [scale=$SCALE,anchor=west] { \includegraphics{$SIG}};" >> $TEX
	else
		# for the last page
		echo "\node at ($XY) [scale=$SCALE,anchor=west] {{\sig $SIG}{\purisa\hspace{31mm}{$Y}\hspace{3mm}\makebox[1em][c]{$M}\hspace{2mm}\makebox[1em][c]{$D}}};" >> $TEX
	fi
	cat <<EOF >> $TEX
    \end{scope}
	\end{tikzpicture}
\end{document}
EOF
}

do_nogrid(){
	cat <<EOF >> $TEX
\documentclass[tikz]{standalone}
\usetikzlibrary{backgrounds}
\usepackage{wx672ctex}
\begin{document}
\begin{tikzpicture}[inner sep=0]
    \node (bg) at (0,0) [anchor=south west] {\includegraphics[width=\paperwidth]{$BG}};
	\begin{scope}
EOF
	if [[ -f "$SIG" ]]
	then
		# for first pages
		echo "\node at ($XY) [scale=$SCALE,anchor=west] { \includegraphics{$SIG}};" >> $TEX
	else
		# for the last page
		echo "\node at ($XY) [scale=$SCALE,anchor=west] {{\sig $SIG}{\purisa\hspace{31mm}$Y\hspace{3mm}\makebox[1em][c]{$M}\hspace{2mm}\makebox[1em][c]{$D}}};" >> $TEX
	fi
	cat <<EOF >> $TEX
    \end{scope}
	\end{tikzpicture}
\end{document}
EOF
}

do_check $1 $2
do_init $@

case "$GRID" in
	g|grid)
		echo "Signing with grid..."
		do_grid
		;;
	n|ng|nogrid)
		echo "Signing without grid..."
		do_nogrid
		;;
	*)
		do_usage
		;;
esac

echo -n Signing...
xelatex $TEX 1>/dev/null

[[ -f "$PDF" ]] || { echo Sorry! Failed to generate PDF file. Please check the $LOG file for details; ls -l $LOG; exit 5; }

{ echo 'DONE!'; ls -l $PDF; }

rm -f $AUX $LOG $TEX
