#!/bin/bash

cat <<EOF | sk --bind "enter:execute(mupdf -r285 -C 'FDF6E3' {} &)+abort" --ansi --color=always
$HOME/lecture_notes/os/slides/os-b.pdf
$HOME/lecture_notes/os/slides/os-a.pdf
$HOME/lecture_notes/network_basics/net-b.pdf
$HOME/lecture_notes/network_basics/net-a.pdf
$HOME/lecture_notes/linux-app/slides/lap-b.pdf
$HOME/lecture_notes/linux-app/slides/lap-a.pdf
$HOME/lecture_notes/linux/linux_intro/linux_intro-b.pdf
$HOME/Documents/os/Modern.Operating.Systems-4e.pdf
$HOME/Documents/os/Operating.System.Concepts.Essentials-2e.pdf
$HOME/Documents/os/Operating.Systems-Design.and.Implementation-3e.pdf
$HOME/Documents/os/Operating.Systems-Internals.and.Design-7e.pdf
$HOME/Documents/Beginning.Linux.Programming-4e.pdf
$HOME/Documents/The.Linux.Programming.Interface.pdf
$HOME/Documents/network/ComputerNetworks-AST-5e.pdf
$HOME/Documents/network/TCPIP.Illustrated-v1.pdf
$HOME/Documents/network/Computer.Networking-A.Top.Down.Approach-6e.pdf
$HOME/lecture_notes/network_basics/figs/state_stevens-crop.pdf
/usr/share/doc/texlive-doc/generic/pgf/pgfmanual.pdf
$HOME/texmf/doc/latex/symbols-a4.pdf
$HOME/texmf/doc/latex/ch8.pdf
$HOME/git/syk-netbook/04-ip.pdf
$HOME/texmf/doc/latex/swfu/timetable/timetable.pdf
EOF
