#!/bin/bash

[[ -n "$2" ]] || { cat <<EOF
`basename $0` - Convert text into an image.

Usage: $0 <text> <Image name> [width] [pointsize]

      text - text you want to say
Image name - name of the generated image
     width - canvas width, default to 640x
 pointsize - font size, default to 36
EOF
exit 4;
}

IMG="$2"
TXT="$1"
WIDTH='640x'; [[ -n "$3" ]] && WIDTH=$3
PSIZE='36'; [[ -n "$4" ]] && PSIZE=$4
# convert -list font | grep CJK
convert -font 'Noto-Sans-CJK-SC' -pointsize $PSIZE -size $WIDTH caption:"$TXT" $IMG
