#!/bin/bash

CHROME="/usr/bin/x-www-browser"
QB="/usr/bin/qutebrowser --target window"

baidupan(){
    bash -c "$QB https://pan.baidu.com &"
}

techbooks(){
	# jkxjxxz:swfcxs
	bash -c "$QB https://cs3/tech &"
}
#calibre2(){
#	# calibre:1984
#	bash -c "$QB http://pub/library &"
#}
#calibre3(){
#	# sensitive:1989
#	bash -c "$QB http://pub/sensitive &"
#}

dingding(){
	bash -c "$QB https://im.dingtalk.com &"
}

# ff(){
# 	firefox -url "data:text/html;charset=utf-8,<!DOCTYPE html><html><body><script>window.open("https://gmail.com", "_blank","menubar=no,location=no,toolbar=no")<%2Fscript><%2Fbody><%2Fhtml>"
# }

gcal(){
  bash -c "$QB https://www.google.com/calendar/render &"
}

gcontacts(){
	bash -c "$QB https://contacts.google.com &"
}

gdrawing(){
  bash -c "$QB https://docs.google.com/drawings/create?usp=apps_start&hl=en &"
}

gdrive(){
  bash -c "$QB https://drive.google.com/drive/#my-drive &"
}

github(){
	bash -c "$QB https://github.com &"
}

gitlab(){
	bash -c "$QB https://gitlab.swfu.edu.cn &"
}

gkeep(){
  bash -c "$QB https://keep.google.com &"
}

gmail(){
  bash -c "$QB https://mail.google.com &"
}

gmailoffline(){
  bash -c "$CHROME https://mail.google.com/mail/mu/?mui=ca &"
}

gmaps(){
	QUERY=""
	for WORD in $@; do
		QUERY="$QUERY%20$WORD"
	done
	bash -c "$QB https://www.google.com/maps/search/$QUERY &"
}

google(){
  QUERY=""
  echo "Googling: $@"
  for WORD in $@; do
    QUERY="$QUERY%20$WORD"
  done
  bash -c "$QB https://www.google.com/search?q=$QUERY &"
}

ddg(){
  QUERY=""
  echo "duckduckgo: $@"
  for WORD in $@; do
    QUERY="$QUERY%20$WORD"
  done
  bash -c "$QB https://duckduckgo.com/?q=$QUERY &"
}

gphotos(){
	bash -c "$QB https://photos.google.com &"
}

grammarly(){
	bash -c "$QB https://app.grammarly.com/ &"
}

hangouts(){
  bash -c "$QB https://hangouts.google.com/ &"
}

jd(){
	bash -c "$QB http://jd.com &"
}

lecturenotes(){
	bash -c "$QB http://cs2.swfu.edu.cn/~wx672/lecture_notes &"
}

lizhifm(){
  bash -c "$QB http://www.lizhi.fm/label/24229953853202224/ &"
}

lucidchart(){
  bash -c "$QB https://www.lucidchart.com/documents &"
}

meituan(){
	bash -c "$QB http://km.meituan.com/ &"
}

moodle(){
  bash -c "$QB http://cs6.swfu.edu.cn/moodle/ &"
}

music163(){
  bash -c "$QB http://music.163.com/#/my/ &"
}

pixlr(){
  bash -c "$QB http://pixlr.com/editor &"
}

q(){
	bash -c "$QB $1 &"
}

qq(){
  bash -c "$QB http://w.qq.com/ &"
}

eastmoney(){
	bash -c "$QB http://i.eastmoney.com/stock.html &"
}

emstock(){
	bash -c "$QB http://i.eastmoney.com/stock.html &"
}

sinastock(){
	bash -c "$QB http://i.finance.sina.com.cn &"
}

taobao(){
  bash -c "$QB http://www.taobao.com/ &"
}

telegram(){
    bash -c "$QB https://web.telegram.org &"
}

timeit(){
	bash -c "$QB http://timeit.swfu.edu.cn/attendance/all &"
}

timer(){
  bash -c "$QB http://www.timer-tab.com &"
}

travelogs(){
	bash -c "$QB http://cs2.swfu.edu.cn/~wx672/travelogs &"
}

twitter(){
	bash -c "$QB https://twitter.com &"
}

wechat(){
  bash -c "$QB https://wx2.qq.com/ &"
}

ximalaya(){
	bash -c "$QB https://www.ximalaya.com/yinyue/235694/ &"
}

youtube(){
  bash -c "$QB https://youtube.com &"
}

zhifubao(){
	bash -c "$QB https://my.alipay.com &"
}

zhihu(){
  bash -c "$QB http://www.zhihu.com/notifications &"
}
