#!/bin/bash

CHROME="/usr/bin/x-www-browser"
QB="/usr/bin/qutebrowser"
QBW="/usr/bin/qutebrowser --target window"

baidupan(){
    bash -c "$QBW https://pan.baidu.com" &>/dev/null &
}

techbooks(){
	# jkxjxxz:swfcxs
	bash -c "$QB https://cs3/tech" 2>/dev/null &
}
#calibre2(){
#	# calibre:1984
#	bash -c "$QB http://pub/library" 2>/dev/null &
#}
#calibre3(){
#	# sensitive:1989
#	bash -c "$QB http://pub/sensitive" 2>/dev/null &
#}

dingding(){
	bash -c "$QBW https://im.dingtalk.com" 2>/dev/null &
}

ff(){
	firefox -url 'data:text/html;charset=utf-8,<!DOCTYPE html><html><body><script>window.open("https://gmail.com", "_blank","menubar=no,location=no,toolbar=no")<%2Fscript><%2Fbody><%2Fhtml>'
}

gcal(){
  bash -c "$QBW https://www.google.com/calendar/render" 2>/dev/null &
}

gcontacts(){
	bash -c "$QBW https://contacts.google.com" 2>/dev/null &
}

gdrawing(){
  bash -c "$QBW https://docs.google.com/drawings/create?usp=apps_start&hl=en" 2>/dev/null &
}

gdrive(){
  bash -c "$QBW https://drive.google.com/drive/#my-drive" 2>/dev/null &
}

github(){
	bash -c "$QBW https://github.com" 2>/dev/null &
}

gitlab(){
	bash -c "$QBW https://gitlab.swfu.edu.cn" 2>/dev/null &
}

gkeep(){
  bash -c "$QBW https://keep.google.com" 2>/dev/null &
}

gmail(){
  bash -c "$QBW https://mail.google.com" 2>/dev/null &
}

gmailoffline(){
  bash -c "$CHROME https://mail.google.com/mail/mu/?mui=ca" 2>/dev/null &
}

gmaps(){
	QUERY=""
	for WORD in $@; do
		QUERY="$QUERY%20$WORD"
	done
	bash -c "$QBW https://www.google.com/maps/search/$QUERY" 2>/dev/null &
}

google(){
  QUERY=""
  echo "Googling: $@"
  for WORD in $@; do
    QUERY="$QUERY%20$WORD"
  done
  bash -c "$QB https://www.google.com/search?q=$QUERY" 2>/dev/null &
}

ddg(){
  QUERY=""
  echo "duckduckgo: $@"
  for WORD in $@; do
    QUERY="$QUERY%20$WORD"
  done
  bash -c "$QB https://duckduckgo.com/?q=$QUERY" 2>/dev/null &
}

gphotos(){
	bash -c "$QBW https://photos.google.com" 2>/dev/null &
}

grammarly(){
	bash -c "$QB https://app.grammarly.com/" 2>/dev/null &
}

hangouts(){
  bash -c "$QBW https://hangouts.google.com/" 2>/dev/null &
}

jd(){
	bash -c "$QBW http://jd.com" 2>/dev/null &
}

jwc(){
	bash -c "$QBW http://jwc.swfu.edu.cn" 2>/dev/null &
}

lecturenotes(){
	bash -c "$QB http://cs2.swfu.edu.cn/~wx672/lecture_notes" 2>/dev/null &
}

lizhifm(){
  bash -c "$QB http://www.lizhi.fm/label/24229953853202224/" 2>/dev/null &
}

lucidchart(){
  bash -c "$QBW https://www.lucidchart.com/documents" 2>/dev/null &
}

meituan(){
	bash -c "$QBW http://km.meituan.com/" 2>/dev/null &
}

moodle(){
  bash -c "$QBW http://cs6.swfu.edu.cn/moodle/" 2>/dev/null &
}

music163(){
  bash -c "$QBW http://music.163.com/#/my/" 2>/dev/null &
}

pixlr(){
  bash -c "$QBW http://pixlr.com/editor" 2>/dev/null &
}

q(){
	bash -c "$QB $1" 2>/dev/null &
}

qq(){
  bash -c "$QBW http://w.qq.com/" 2>/dev/null &
}

emstock(){
	bash -c "$QBW http://i.eastmoney.com/stock.html" 2>/dev/null &
}

sinastock(){
	bash -c "$QBW http://i.finance.sina.com.cn" 2>/dev/null &
}

taobao(){
  bash -c "$QBW http://www.taobao.com/" 2>/dev/null &
}

telegram(){
    bash -c "$QBW https://web.telegram.org" 2>/dev/null &
}

timeit(){
	bash -c "$QBW http://timeit.swfu.edu.cn/attendance/all" 2>/dev/null &
}

timer(){
  bash -c "$QBW http://www.timer-tab.com" 2>/dev/null &
}

travelogs(){
	bash -c "$QBW http://cs2.swfu.edu.cn/~wx672/travelogs" 2>/dev/null &
}

twitter(){
	bash -c "$QBW https://twitter.com" 2>/dev/null &
}

wechat(){
  bash -c "$QBW https://wx2.qq.com/" 2>/dev/null &
}

youtube(){
  bash -c "$QBW https://youtube.com" 2>/dev/null &
}

zhifubao(){
	bash -c "$QBW https://my.alipay.com" 2>/dev/null &
}

zhihu(){
  bash -c "$QBW http://www.zhihu.com/notifications" 2>/dev/null &
}
