(deftheme creame
  "Created 2021-09-05.")

(custom-theme-set-variables
 'creame
 '(menu-bar-mode nil)
 '(tool-bar-mode nil))

(custom-theme-set-faces
 'creame
 '(fringe ((t (:background "#f0e5da"))))
 '(region ((t (:background "#fda50f" :foreground "#000000"))))
 '(show-paren-match ((t (:background "#f0e5da" :foreground "#00ff00" :bold t))))
 '(show-paren-mismatch ((t (:background "#f0e5da" :foreground "#ff0000" :bold t))))
 '(minibuffer-prompt ((t (:weight bold :foreground "#000000"))))
 '(isearch ((t (:background "#7d7165" :foreground "#000000" :bold t))))
 '(lazy-highlight ((t (:background "#c4baaf" :foreground "#000000"))))
 '(link ((t (:underline t))))
 '(mode-line ((t (:box (:line-width -1 :color "#c4baaf") :background "#dbd0c5" :foreground "#000000"))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color "#c4baaf") :background "#f0e5da" :foreground "#c4baaf"))))
 '(font-lock-keyword-face ((t (:bold t))))
 '(font-lock-function-name-face ((t (:bold t))))
 '(font-lock-variable-name-face ((t (:foreground "#000000"))))
 '(font-lock-warning-face ((t (:foreground "#000000" :underline (:color "#ff0000" :style wave)))))
 '(font-lock-builtin-face ((t (:bold t))))
 '(font-lock-variable-name-face ((t (:foreground "#000000" :italic t))))
 '(font-lock-constant-face ((t (:bold t :italic t))))
 '(font-lock-type-face ((t (:italic t))))
 '(font-lock-preprocessor-face ((t (:italic t))))
 '(font-lock-comment-face ((t (:foreground "#7d7165" :italic t))))
 '(font-lock-string-face ((t (:foreground "#3c5e2b"))))
 '(font-lock-doc-face ((t (:inherit font-lock-comment-face))))
 '(line-number ((t (:foreground "#c4baaf"))))
 '(vertical-border ((t (:foreground "#c4baaf"))))
 '(company-tooltip ((t (:background "#dbd0c5" :foreground "#000000"))))
 '(company-tooltip-selection ((t (:background "#c4baaf" :foreground "#000000"))))
 '(company-tooltip-common ((t (:bold t))))
 '(company-tooltip-common-selection ((t (:bold t))))
 '(company-scrollbar-bg ((t (:background "#c4baaf"))))
 '(company-scrollbar-fg ((t (:background "#7d7165"))))
 '(company-tooltip-annotation-selection ((t (:background "#c4baaf" :foreground "#000000" :italic t))))
 '(company-tooltip-annotation ((t (:background "#dbd0c5" :foreground "#7d7165" :italic t))))
 '(hl-line ((t (:background "#dbd0c5"))))
 '(ido-first-match ((t (:bold t))))
 '(ido-only-match ((t (:bold t))))
 '(ido-subdir ((t (:italic t))))
 '(ido-virtual ((t (:foreground "#7d7165"))))
 ;; '(org-table ((t (:foreground "#7d7165"))))
 '(default ((t (:background "#f0e5da" :foreground "#000000")))))

(provide-theme 'creame)
